name: c++ CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push: 
    branches: CANOSP
  pull_request:
    branches: CANOSP


jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: AdoptOpenJDK/install-jdk@2f15d3f82051aa50984186fc1184467d0d9f87d0 # v1.1.1
        with:
          version: '11'
          targets: 'JAVA_HOME'
          impl: 'openj9'
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: create build directory
        run: cd ./perf-tool && mkdir build
      - name: cmake build
        run: cmake ..
        working-directory: ./perf-tool/build
      - name: make clean
        run: make clean
        working-directory: ./perf-tool/build
      - name: make
        run: make
        working-directory: ./perf-tool/build
      - name: run agent
        run: $JAVA_HOME/bin/java -agentpath:$PWD/libagent.so -version
        working-directory: ./perf-tool/build


